CREATE TABLE dbo.Turno 
(
	IdTurno INT IDENTITY(1,1) NOT NULL,
	FechaTurno DATE NOT NULL,
	Estado SMALLINT NOT NULL,
	Observacion VARCHAR(300) NULL,

	CONSTRAINT PK_Turno
		PRIMARY KEY CLUSTERED (IdTurno),
);