CREATE TABLE dbo.Pago 
(
	IdPago INT IDENTITY(1,1),
	Concepto TINYINT NOT NULL,
	Fecha DATETIME NOT NULL DEFAULT GETDATE(),
	Monto MONEY NOT NULL,
	Estado TINYINT NOT NULL DEFAULT 1,
	Observacion VARCHAR(1000) NULL,

	CONSTRAINT PK_Pago
		PRIMARY KEY CLUSTERED (IdPago),
);