DROP TABLE IF EXISTS dbo.Medico;

CREATE TABLE dbo.Medico 
(
	IdMedico dbo.idMedico IDENTITY(1,1) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,

	CONSTRAINT PK_Medico
		PRIMARY KEY CLUSTERED (IdMedico),
);