DROP TABLE IF EXISTS dbo.Pago;

CREATE TABLE dbo.Pago 
(
	IdPago dbo.idPago IDENTITY(1,1) NOT NULL,
	Concepto TINYINT NOT NULL,
	Fecha DATETIME NOT NULL DEFAULT GETDATE(),
	Monto MONEY NOT NULL DEFAULT 0,
	Estado TINYINT NOT NULL DEFAULT 1,
	Observacion dbo.observacion NULL,

	CONSTRAINT PK_Pago
		PRIMARY KEY CLUSTERED (IdPago),
);