CREATE TABLE Pago (
	idPago INT PRIMARY KEY IDENTITY(1,1),
	concepto TINYINT NOT NULL,
	fecha DATETIME NOT NULL DEFAULT GETDATE(),
	monto MONEY NOT NULL,
	estado TINYINT NOT NULL DEFAULT 1,
	observacion VARCHAR(1000),
);