DROP TYPE IF EXISTS dbo.idPaciente;
CREATE TYPE dbo.idPaciente FROM INT NOT NULL;

DROP TYPE IF EXISTS dbo.idMedico;
CREATE TYPE dbo.idMedico FROM INT NOT NULL;

DROP TYPE IF EXISTS dbo.idEspecialidad;
CREATE TYPE dbo.idEspecialidad FROM INT NOT NULL;

DROP TYPE IF EXISTS dbo.idHistoria;
CREATE TYPE dbo.idHistoria FROM INT NOT NULL;

DROP TYPE IF EXISTS dbo.idPais;
CREATE TYPE dbo.idPais FROM CHAR(3) NOT NULL;

DROP TYPE IF EXISTS dbo.idPago;
CREATE TYPE dbo.idPago FROM INT NOT NULL;

DROP TYPE IF EXISTS dbo.idConcepto;
CREATE TYPE dbo.idConcepto FROM TINYINT NOT NULL;

DROP TYPE IF EXISTS dbo.idEstado;
CREATE TYPE dbo.idEstado FROM SMALLINT NOT NULL;

DROP TYPE IF EXISTS dbo.idTurno;
CREATE TYPE dbo.idTurno FROM INT NOT NULL;

DROP TYPE IF EXISTS dbo.observacion;
CREATE TYPE dbo.observacion FROM NVARCHAR(2000) NULL;