IF TYPE_ID(N'dbo.idPaciente') IS NULL
	EXEC(N'CREATE TYPE dbo.idPaciente FROM INT NOT NULL;');
GO

IF TYPE_ID(N'dbo.idMedico') IS NULL
	EXEC(N'CREATE TYPE dbo.idMedico FROM INT NOT NULL;');
GO

IF TYPE_ID(N'dbo.idEspecialidad') IS NULL
	EXEC(N'CREATE TYPE dbo.idEspecialidad FROM INT NOT NULL;');
GO

IF TYPE_ID(N'dbo.idHistoria') IS NULL
	EXEC(N'CREATE TYPE dbo.idHistoria FROM INT NOT NULL;');
GO

IF TYPE_ID(N'dbo.idPais') IS NULL
	EXEC(N'CREATE TYPE dbo.idPais FROM CHAR(3) NOT NULL;');
GO

IF TYPE_ID(N'dbo.idPago') IS NULL
	EXEC(N'CREATE TYPE dbo.idPago FROM INT NOT NULL;');
GO

IF TYPE_ID(N'dbo.idConcepto') IS NULL
	EXEC(N'CREATE TYPE dbo.idConcepto FROM TINYINT NOT NULL;');
GO

IF TYPE_ID(N'dbo.idEstado') IS NULL
	EXEC(N'CREATE TYPE dbo.idEstado FROM SMALLINT NOT NULL;');
GO

IF TYPE_ID(N'dbo.idTurno') IS NULL
	EXEC(N'CREATE TYPE dbo.idTurno FROM INT NOT NULL;');
GO

IF TYPE_ID(N'dbo.observacion') IS NULL
	EXEC(N'CREATE TYPE dbo.observacion FROM NVARCHAR(2000) NULL;');
GO
