import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "2rem", borderBottom: "1px solid #ccc" }}>
          <nav>
            <ul style={{ display: "flex", gap: "1rem", listStyle: "none" }}>
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/about/team">Team</Link>
            </ul>
          </nav>
        </header>
        <main style={{ padding: "2rem" }}>{children}</main>
      </body>
    </html>
  );
}
