USE DBA_LAB_CORE;
GO

SELECT SYSDATETIME() AS HoraAntes;

INSERT dbo.Cliente(Nombre, Ciudad)
VALUES 
	('Conservar Antes Incidente', 'Santo Domingo');

---

BACKUP LOG DBA_LAB_CORE
TO DISK = N'B:\SQLBackups\Log\DBA_LAB_CORE\DBA_LAB_CORE_LOG_03.trn'
WITH 
	INIT, CHECKSUM, STATS = 10;

---

SELECT SYSDATETIME() AS HoraInmediatamenteAntesDelDelete;
DELETE dbo.Cliente WHERE Nombre LIKE 'Cliente Post%';
SELECT SYSDATETIME() AS HoraDespuesDelDelete;

---

BACKUP LOG DBA_LAB_CORE
TO DISK = N'B:\SQLBackups\Log\DBA_LAB_CORE\DBA_LAB_CORE_LOG_04.trn'
WITH INIT, CHECKSUM;

---

RESTORE VERIFYONLY
FROM DISK = N'B:\SQLBackups\Full\DBA_LAB_CORE\DBA_LAB_CORE_FULL.bak';

RESTORE FILELISTONLY
FROM DISK = N'B:\SQLBackups\Full\DBA_LAB_CORE\DBA_LAB_CORE_FULL.bak';

---

RESTORE DATABASE DBA_LAB_RESTORE
FROM DISK = N'B:\SQLBackups\Full\DBA_LAB_CORE\DBA_LAB_CORE_FULL.bak'
WITH 
	NORECOVERY,
	MOVE 'DBA_LAB_CORE_Data' TO N'B:\SQLData\DBA_LAB_RESTORE.mdf',
	MOVE 'DBA_LAB_CORE_Log' TO N'B:\SQLLogs\DBA_LAB_RESTORE.ldf',
	REPLACE, STATS=10;

---
RESTORE DATABASE [DBA_LAB_RESTORE]
FROM DISK = N'B:\SQLBackups\Differential\DBA_LAB_CORE\DBA_LAB_CORE_DIFF.bak'
WITH NORECOVERY, STATS = 10;

RESTORE LOG [DBA_LAB_RESTORE] 
FROM DISK = N'B:\SQLBackups\Log\DBA_LAB_CORE\\DBA_LAB_CORE_LOG_01.trn' 
WITH NORECOVERY, STATS = 10;

RESTORE LOG [DBA_LAB_RESTORE] 
FROM DISK = N'B:\SQLBackups\Log\DBA_LAB_CORE\DBA_LAB_CORE_backup_2026_09_15_104500_9327812.trn' 
WITH NORECOVERY, STATS = 10;

RESTORE LOG [DBA_LAB_RESTORE] 
FROM DISK = N'B:\SQLBackups\Log\DBA_LAB_CORE\DBA_LAB_CORE_backup_2026_09_15_110001_8595440.trn' 
WITH NORECOVERY, STATS = 10;

RESTORE LOG [DBA_LAB_RESTORE] 
FROM DISK = N'B:\SQLBackups\Log\DBA_LAB_CORE\DBA_LAB_CORE_LOG_03.trn' 
WITH NORECOVERY, STATS = 10;

RESTORE LOG [DBA_LAB_RESTORE] 
FROM DISK = N'B:\SQLBackups\Log\DBA_LAB_CORE\DBA_LAB_CORE_LOG_04.trn' 
WITH 
	STOPAT='2026-09-15T11:00:21',
	RECOVERY, STATS = 10;

---

USE DBA_LAB_RESTORE;
GO

SELECT * 
FROM dbo.Cliente 
ORDER BY ClienteID;